# Generated by Django 6.0.4 on 2026-08-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(to='myApp.department'),
        ),
    ]
