# Generated by Django 6.0.4 on 2026-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerationform',
            name='nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
