# Generated by Django 6.0.4 on 2026-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_registerationform_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationform',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
